### ISSUE TITLE
Add `getEvent` method

### ISSUE THREAD

**Issue by grandprixgp** [gigobyte/HLTV#19]
Do you have any plans to add events?

Do you accept contributions?

**Comment by gigobyte** [comment]
Players and events are what I'm planning so far, the development has slowed down because of personal issues, but I'll be able to work on this package again soon.

Of course I accept contributions! But I think I might have to add a tslint/prettier config so that the code style remains the same through the whole codebase.

**Comment by grandprixgp** [comment]
Yeah no problem I'm really not that experienced with JS/NodeJS so if I did contribute anything it'd probably be small and done by example (I've learnt quite a bit from this project). Looking forward to those features!

Great job so far, saved me a bunch of time. I'm writing a HLTV interface for a Discord bot :) [example1](http://i.imgur.com/Zrb1kxi.png) [example2](http://i.imgur.com/lGM6eNG.png)

**Comment by gigobyte** [comment]
Added in version 2.8.0
