### ISSUE TITLE
Cloudflare access denied unexpectedly?

### ISSUE THREAD

**Issue by sanjanaabeykoon2** [gigobyte/HLTV#552]
Hi there,
I am using the getResults method and filtering with startdate as yesterdays date and the end date as today's to return the list of results that resulted in the last day. It was originally working but now returns a Cloudflare error? Not sure what changed to make this a problem for cloudflare - when I use the example on the npm api page (by which you filter using the eventId ) I was able to return a big list of results however I can see on hltv's website that there are not many results in the last day so why is this smaller result causing a cloudflare issue? Would really appreciate the advice!
Thanks,

**Comment by Revilum** [comment]
probably related to #497 but make sure that the request is in the correct format as this can cause a lot of issues

**Comment by sanjanaabeykoon2** [comment]
Thanks so much and sorry for getting back so slowly! It was indeed the format of my request which after editing came out fine!
Would you by any chance know of a mechanism for retrieving stats for multiple teams: I have a list of about 40+ teams and I want to iterate through, retrieving the teamStats using getTeamStats. 
If i simply loop through and make that singular api call I will definitely end up getting lots of access denied messages so I've tried using the below line to implement a delay but still seem to get cloudflare triggered 
await new Promise(resolve => setTimeout(resolve, 10000 * index));
Any suggestions would really be appreciated!

**Comment by Revilum** [comment]
There are 2 reasons why a Cloudflare access denied happens
- Too may request at once (can be fixed by adding `delayBetweenPageRequests` for functions that send more than one request) usually a number betwwen 300 -500 is enough to stop getting the error.
- The second Type happens randomly because each request is masked as a different new webbrowser to achieve a higher requests/time ration before getting banned. The actual "random ban" happens because some browers are banned acessing hltv which is why it there is no pattern for the bans. The only way to fix this is by removing the random browser mask (which honestly should be done because the supposed advantage doesn't exist in 99% of all cases). You could create your own fork of the repository and edit the `src/config.ts` and remove the random useragent or use [mine}(https://www.npmjs.com/package/hltv-next) version but keep in mind that I there are some minor changes to the data than the original version.

**Comment by sanjanaabeykoon2** [comment]
Thanks so much for the quick response! If I were to install your version of the package, will my existing imports and calls to hltv in my code still work if I uninstall the original hltv npm package first? I am going to try using yours if not!

**Comment by Revilum** [comment]
it will still work. the only thing that you need to change is `require('hltv')` to `require('hltv-next')`

**Comment by AuroraDysis** [comment]
> it will still work. the only thing that you need to change is `require('hltv')` to `require('hltv-next')`

@Revilum 
Thanks for your awesome work. Do you have any plans to open source in a new repo, or open a pull request on this repo?

**Comment by Revilum** [comment]
> > it will still work. the only thing that you need to change is `require('hltv')` to `require('hltv-next')`
> 
> @Revilum Thanks for your awesome work. Do you have any plans to open source in a new repo, or open a pull request on this repo?

The source of the repo is already publicly available [here](https://github.com/Zsunamy/HLTV) Note that the documentation might be a bit out of date but I'll work on that later today. Most of its changes are already pull requests anyway and as long as @gigobyte doesn't start reviewing the current pull request, I don't see the point of creating new Pull Requests. Also there are some changes that I made are just for my specific usecase.
But I'm happy that other people are interested in my continuation and feel free to ask any questions!

**Comment by Revilum** [comment]
should be resolved with 7a88867
